import type { Metadata } from 'next'
import { Manrope, Roboto } from 'next/font/google'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import '@ant-design/v5-patch-for-react-19'
import { ConfigProvider } from 'antd'
import { uiConfig } from '@/config/ui-config'
import '@/assets/styles/global.scss'
import { getServerSession } from 'next-auth'
import { Providers } from '@/provider'
import { authOptions } from '@/lib/auth'
import React from 'react'
import { ToastContainer } from 'react-toastify'

// @ts-ignore
const manrope = Manrope({
    variable: '--font-manrope',
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700'],
    style: 'normal',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const session = await getServerSession(authOptions)

    return (
        <html lang="en">
            <body className={`antialiased`}>
                <Providers session={session}>
                    <ConfigProvider {...uiConfig}>
                        <AntdRegistry>{children}</AntdRegistry>
                    </ConfigProvider>
                    <ToastContainer />
                </Providers>
            </body>
        </html>
    )
}
